#!/usr/bin/env python
import json
import argparse
from pyroute2 import Console
from pyroute2 import Server

argp = argparse.ArgumentParser()
for spec in (('-a', '[S] IP address to listen on'),
             ('-c', '[C] Command line to run'),
             ('-d', '[C,S] Debug spec'),
             ('-m', 'set mode (C,S)'),
             ('-p', '[S] Port to listen on'),
             ('-r', '[C] Load rc file'),
             ('-s', '[C,S] Load sources from a json file')):
    argp.add_argument(spec[0], help=spec[1])
args = argp.parse_args()
commands = []
sources = None
if args.s:
    with open(args.s, 'r') as f:
        sources = json.loads(f.read())

if args.m in ('S', 'server'):
    server = Server(address=args.a or 'localhost',
                    port=int(args.p) or 8080,
                    debug=args.d,
                    sources=sources)
    server.serve_forever()
else:
    console = Console(debug=args.d, sources=sources)
    if args.r:
        console.loadrc(args.r)

    if args.c:
        commands.append(args.c)
        console.interact(readfunc=lambda x: commands.pop(0))
    else:
        console.interact()
