from enum import IntEnum


class MessageType(IntEnum):
    DISCOVER = 1
    OFFER = 2
    REQUEST = 3
    DECLINE = 4
    ACK = 5
    NAK = 6
    RELEASE = 7
    INFORM = 8


class Option(IntEnum):
    SUBNET_MASK = 1
    TIME_OFFSET = 2
    ROUTER = 3
    DNS_SERVER = 6
    HOST_NAME = 12
    DOMAIN_NAME = 15
    BROADCAST_ADDRESS = 28
    REQUESTED_IP_ADDRESS = 50
    IP_ADDRESS_LEASE_TIME = 51
    DHCP_MESSAGE_TYPE = 53
    SERVER_IDENTIFIER = 54
    PARAMETER_REQUEST_LIST = 55
    MAX_MSG_SIZE = 57
    RENEWAL_TIME = 58
    REBINDING_TIME = 59
    VENDOR_CLASS_IDENTIFIER = 60
    CLIENT_IDENTIFIER = 61
    PADDING = 255


class Parameter(IntEnum):
    SUBNET_MASK = 1  # Subnet Mask
    TIME_OFFSET = 2  # Time Offset
    ROUTER = 3  # Router
    TIME_SERVER = 4  # Time Server
    NAME_SERVER = 5  # Name Server
    DOMAIN_NAME_SERVER = 6  # Domain Name Server (DNS)
    LOG_SERVER = 7  # Log Server
    COOKIE_SERVER = 8  # Cookie Server
    LPR_SERVER = 9  # Line Printer Server
    IMPRESS_SERVER = 10  # Impress Server
    RESOURCE_LOCATION_SERVER = 11  # Resource Location Server
    HOST_NAME = 12  # Host Name
    BOOT_FILE_SIZE = 13  # Boot File Size
    MERIT_DUMP_FILE = 14  # Merit Dump File
    DOMAIN_NAME = 15  # Domain Name
    SWAP_SERVER = 16  # Swap Server
    ROOT_PATH = 17  # Root Path
    EXTENSIONS_PATH = 18  # Extensions Path
    IP_FORWARDING = 19  # IP Forwarding Enable/Disable
    NON_LOCAL_SOURCE_ROUTING = 20  # Non-Local Source Routing Enable/Disable
    POLICY_FILTER = 21  # Policy Filter
    MAX_DATAGRAM_REASSEMBLY = 22  # Maximum Datagram Reassembly Size
    DEFAULT_TTL = 23  # Default IP Time-to-Live
    PATH_MTU_AGING_TIMEOUT = 24  # Path MTU Aging Timeout
    PATH_MTU_PLATEAU_TABLE = 25  # Path MTU Plateau Table
    INTERFACE_MTU = 26  # Interface MTU
    ALL_SUBNETS_LOCAL = 27  # All Subnets Are Local
    BROADCAST_ADDRESS = 28  # Broadcast Address
    PERFORM_MASK_DISCOVERY = 29  # Perform Mask Discovery
    MASK_SUPPLIER = 30  # Mask Supplier
    PERFORM_ROUTER_DISCOVERY = 31  # Perform Router Discovery
    ROUTER_SOLICITATION_ADDRESS = 32  # Router Solicitation Address
    STATIC_ROUTE = 33  # Static Route
    TRAILER_ENCAPSULATION = 34  # Trailer Encapsulation
    ARP_CACHE_TIMEOUT = 35  # ARP Cache Timeout
    ETHERNET_ENCAPSULATION = 36  # Ethernet Encapsulation
    TCP_DEFAULT_TTL = 37  # TCP Default TTL
    TCP_KEEPALIVE_INTERVAL = 38  # TCP Keepalive Interval
    TCP_KEEPALIVE_GARBAGE = 39  # TCP Keepalive Garbage
    NIS_DOMAIN = 40  # Network Information Service Domain
    NIS_SERVERS = 41  # NIS Servers
    NTP_SERVERS = 42  # NTP Servers
    VENDOR_SPECIFIC_INFORMATION = 43  # Vendor Specific Information
    NETBIOS_NAME_SERVER = 44  # NetBIOS over TCP/IP Name Server
    NETBIOS_DDG_SERVER = 45  # NetBIOS Datagram Distribution Server
    NETBIOS_NODE_TYPE = 46  # NetBIOS Node Type
    NETBIOS_SCOPE = 47  # NetBIOS Scope
    X_WINDOW_FONT_SERVER = 48  # X Window System Font Server
    X_WINDOW_DISPLAY_MANAGER = 49  # X Window System Display Manager
    REQUESTED_IP_ADDRESS = 50  # Requested IP Address
    IP_ADDRESS_LEASE_TIME = 51  # IP Address Lease Time
    OPTION_OVERLOAD = 52  # Option Overload
    DHCP_MESSAGE_TYPE = 53  # DHCP Message Type
    SERVER_IDENTIFIER = 54  # Server Identifier
    PARAMETER_REQUEST_LIST = 55  # Parameter Request List
    MESSAGE = 56  # Message
    MAX_DHCP_MESSAGE_SIZE = 57  # Maximum DHCP Message Size
    RENEWAL_TIME_VALUE = 58  # Renewal (T1) Time Value
    REBINDING_TIME_VALUE = 59  # Rebinding (T2) Time Value
    CLASS_IDENTIFIER = 60  # Vendor Class Identifier
    CLIENT_IDENTIFIER = 61  # Client Identifier
    NETWARE_IP_DOMAIN = 62  # NetWare/IP Domain Name
    NETWARE_IP_OPTION = 63  # NetWare/IP Option
    NIS_PLUS_DOMAIN = 64  # NIS+ Domain
    NIS_PLUS_SERVERS = 65  # NIS+ Servers
    TFTP_SERVER_NAME = 66  # TFTP Server Name
    BOOTFILE_NAME = 67  # Bootfile Name
    MOBILE_IP_HOME_AGENT = 68  # Mobile IP Home Agent
    SMTP_SERVER = 69  # Simple Mail Transport Protocol Server
    POP3_SERVER = 70  # Post Office Protocol v3 Server
    NNTP_SERVER = 71  # Network News Transport Protocol Server
    DEFAULT_WWW_SERVER = 72  # Default World Wide Web Server
    DEFAULT_FINGER_SERVER = 73  # Default Finger Server
    DEFAULT_IRC_SERVER = 74  # Default Internet Relay Chat Server
    STREETTALK_SERVER = 75  # StreetTalk Server
    STDA_SERVER = 76  # StreetTalk Directory Assistance Server
    USER_CLASS_INFORMATION = 77  # User Class Information
    SLP_DIRECTORY_AGENT = 78  # SLP Directory Agent
    SLP_SERVICE_SCOPE = 79  # SLP Service Scope
    RAPID_COMMIT = 80  # Rapid Commit
    CLIENT_FQDN = 81  # Fully Qualified Domain Name
    RELAY_AGENT_INFORMATION = 82  # Relay Agent Information
    INTERNET_STORAGE_NAME_SERVICE = 83  # ISNS
    NDS_SERVERS = 85  # Novell Directory Services Servers
    NDS_TREE_NAME = 86  # Novell Directory Services Tree Name
    NDS_CONTEXT = 87  # Novell Directory Services Context
    BCMCS_CONTROLLER_DOMAIN = 88  # BCMCS Controller Domain Name List
    AUTHENTICATION = 90
    CLIENT_SYSTEM_ARCHITECTURE_TYPE = 93
    CLIENT_NETWORK_INTERFACE_IDENTIFIER = 94
    CLASSLESS_STATIC_ROUTE = 121
    DOMAIN_SEARCH = 119
    PRIVATE_CLASSIC_ROUTE_MS = 249
    PRIVATE_PROXY_AUTODISCOVERY = 252
